### ISSUE TITLE
Probleme mit Anwendung einer Funktion auf mehrere Spalten/Datensatz größer als nur 1 Protein

### ISSUE THREAD

**Issue by hanaros27** [datascience-mobi/2021-topic-03-team-05#3]
Wir haben einen Code geschrieben um den Mittelwert der ähnlicheren Replikate pro Fraktion zu berechnen und dies hat sehr gut funktioniert mit einem Beispieldatensatz, in dem nur ein Protein aus dem ursprünglichen Datensatz selektiert wurde. In dem Subset "test" sind die Zeilen die 3 Replikate einer Fraktion und die Spalte ist das Beispielprotein. Bei "test2" ist es gleich, nur dieses Mal 20 Proteine. Wenn wir versuchen, diesen Code auf den Datensatz mit allen Proteinen anzuwenden bzw. auf "test2", kommen zahlreiche Fehlermeldungen je nach Versuch: z.B. _**incorrect number of dimensions**_, _**Error in r[i1] - r[-length(r):-(length(r) - lag + 1L)] : non-numeric argument to binary operator**_ , usw. Unseren Code kopiere ich unten, falls es dir Sinn ergibt, weil wir gar nicht weiterkommen...

Definieren von Beispielsdatensätzen (tFraction1CtrlAllRepl ist dabei ein Datensatz aus allen Proteinen in den Spalten und den 3 Replikaten der Fraktion 1 in den Zeilen), in denen wir ein Beispielprotein und die dazugehörigen Replikate der Fraktion 1 haben.
```
test <- as.data.frame(tFraction1CtrlAllRepl$"1433B_HUMAN")
colnames(test) <- colnamestourdataset[1]
rownames(test) <- rownamestourdataset[1:3]

test2 <- as.data.frame(tFraction1CtrlAllRepl[1:20])

```
Wir haben dann folgende Funktion definiert, um die Mittelwerte der ähnlicheren Replikate zu ermitteln:

```
selectreplicatesminus = function(x){
  if(abs(x[1,]-x[2,])<abs(x[2,]-x[3,]) && abs(x[1,]-x[2,])<abs(x[1,]-x[3,])) {
    mean(c(x[1,],x[2,]))
  } else if (abs(x[1,]-x[3,])<abs(x[1,]-x[2,]) && abs(x[1,]-x[3,])<abs(x[2,]-x[3,])) {
    mean(c(x[1,],x[3,]))
  } else {
    mean(c(x[2,],x[3,]))
  }
}
```

Wie oben beschrieben, auf den test Datensatz angewendet funktioniert der Code, aber sobald wir ihn über mehrere Proteine laufen lassen wollen klappt das nicht mehr. Haben es folgendermaßen gemacht:

`sapply(as.data.frame(t(test2)), function(x) selectreplicatesminus(x))`

`apply(test2, MARGIN=2, FUN= selectreplicatesminus)`

...und viele andere Versuche die wir in dem Chaos gar nicht mehr finden.

Hast du zufällig einen Plan was wir ändern müssen? Danke im Voraus:)

**Comment by leoniethomas** [comment]
Hey ihr, 
also wenn ihr einen apply anwendet dann nehmt ihr in eurem Fall die daten aus den einzelnen Spalten als vektoren heraus. 
D.h. dass was ihr eurem selectreplicatesminus in dem apply übergibt ist ein vektor. Die Funktion will aber ein data.frame haben. Ihr müsst also einfach immer die kommer aus den eckigen KLammern rausnehmen also anstatt `x[1,]` `x[1]` schreiben. Bei mir läuft der code dann so :)

**Comment by MaikeH25** [comment]
Was genau hast du denn als Dataframe dann benutzt? Mit unserem test-DataFrame klappt es leider immer noch nicht, jetzt kommt die Fehlermeldung
 "Fehler in r[i1] - r[-length(r):-(length(r) - lag + 1L)] : 
  nicht-numerisches Argument für binären Operator" 

Vielleicht haben wir auch einen Schritt vorher vergessen...

**Comment by leoniethomas** [comment]
`path = "/home/lthomas/Documents/Studium/Master/HiWi_DataScience/"
MS_Table <- as.data.frame(t(read.table(paste0(path, "data/RDeeP_HeLa_Mitosis.csv"), header=TRUE, row.names=1, sep = ";")))

tFraction1CtrlAllRepl <- MS_Table[which(grepl("Fraction1_", rownames(MS_Table))),]

test <- as.data.frame(tFraction1CtrlAllRepl$"1433B_HUMAN")
test2 <- as.data.frame(tFraction1CtrlAllRepl[,1:20])
rownames(test) <- rownames(tFraction1CtrlAllRepl)



selectreplicatesminus = function(x){
  if(abs(x[1]-x[2])<abs(x[2]-x[3]) && abs(x[1]-x[2])<abs(x[1]-x[3])) {
    mean(c(x[1],x[2]))
  } else if (abs(x[1]-x[3])<abs(x[1]-x[2]) && abs(x[1]-x[3])<abs(x[2]-x[3])) {
    mean(c(x[1],x[3]))
  } else {
    mean(c(x[2],x[3]))
  }
}

selectreplicatesminus(test$`tFraction1CtrlAllRepl$"1433B_HUMAN"`)
apply(test2, 2, selectreplicatesminus)`

**Comment by leoniethomas** [comment]
funktioniert der code wenn ihr ihn bei euch anwendet ?

**Comment by hanaros27** [comment]
Bei mir wird die folgende Fehlermeldung angezeigt: 
**_Error in test$tFraction1CtrlAllRepl$"1433B_HUMAN" : 
  $ operator is invalid for atomic vectors_**
