### ISSUE TITLE
Maxima Bestimmung

### ISSUE THREAD

**Issue by GyuMinHwang** [datascience-mobi/2021-topic-03-team-05#4]
Also wir haben diesen Code geschrieben und irgenwie haben wir Probleme mit dem Ausführen.
_______________________________________________________________________________________________________________________________
##als funktion definieren, weil for loop ewig langsam ist
Suche_Maxima <- function(x){
   for (i in 1:ncol(tnorm100_AllFractionsCtrlRep1)){        ##iteriert über alle Spalten(jedes Protein) i im Rep1
      x <- tnorm100_AllFractionsCtrlRep1[x, i]                ##definiert x als Wert aus Spalte i
      if (x > x+1 && x-1)                                                ##Idee: Maximum ist ein peak - Wert x ist größer als Werte in direkter Umgebung -> x+1, x-1
         print(x)
   i <- i+1
   }
}

##als apply funktion
tnorm100_AllFractionsCtrlRep1_maxima <- apply(tnorm100_AllFractionsCtrlRep1, 1, Suche_Maxima)
class(tnorm100_AllFractionsCtrlRep1)
show(tnorm100_AllFractionsCtrlRep1_maxima[200])
Suche_Maxima(tnorm100_AllFractionsRNaseRep1[,200])
_______________________________________________________________________________________________________________________________

Also bei mir taucht die Fehlermeldung "Fehler in if (x > x + 1 && x - 1) print(x) : Fehlender Wert, wo TRUE/FALSE nötig ist2
Und aus irgendeinem Grund läuft bei Yasmin der Code durch, aber dafür taucht nur 26 als Wert auf.

Wir vermuten, dass es an der if-loop    @@@liegt. Kannst du vielleicht mal drübber schauen?

**Comment by leoniethomas** [comment]
Hey ihr, habt ihr das markdown mit dem code hochgeladen ? dann kann es mir besser anschauen :)

**Comment by hanaros27** [comment]
@leoniethomas der Code ist in einem File mit dem Namen "Gyu Min.rmd", als Beschreibung steht Issue Meldung :)

**Comment by leoniethomas** [comment]
`Suche_Maxima <- function(x){
   for (i in 1:length(x)){        ##iteriert über alle Spalten(jedes Protein) i im Rep1
                            ##definiert x als Wert aus Spalte i
        if(i != length(x)){
                if(x[i] > x[i+1] && x[i] > x[i-1]){                                  ##Idee: Maximum ist ein peak - Wert x ist größer als Werte in direkter Umgebung -> x+1, x-1
                    print(x[i])
                }
                
        }else{
                 if(x[i] > x[i-1]){                                  ##Idee: Maximum ist ein peak - Wert x ist größer als Werte in direkter Umgebung -> x+1, x-1
                    print(x[i])
                }
        }
   #i <- i+1
   }
}`

**Comment by leoniethomas** [comment]
Hey, ich hab mich nochmal dran probiert und das Rmd file in euer repo gepushed. Ich hab mal mir zusammengebastelt wie ihr das dataframe erstellt, damit ihr schauen könnt ob ich es diesmal auch auf den richtigen dataframe angewendet habe. Das Problem war noch, dass es ja auch kein `x[i-1]` element bei `i <- 1` gibt daher muss es noch einen extra else option für diesen Fall geben.

**Comment by GyuMinHwang** [comment]
hey, sorry, dass ich erst jetzt antworte. soweit ich das jetzt gesehen habe, läuft code problemlos über das richtige dataframe. vielen lieben dank :)

**Comment by YasminMetzler** [comment]
Hey Leonie,
kurze Frage zu deinem Code. Wir haben ihn durchlaufen lassen und generell spuckt er uns Werte aus, allerdings nur die globalen Maxima. Die lokalen Maxima werden komischerweise nicht ausgegeben. Kontrolliert haben wir das mit Hilfe des Proteins in Spalte 200. Das hat 4 oder 5 Maxima aber unser Code gibt nur das globale Maxima aus. 
Wir können uns allerdings nicht erklären wieso, da uns kein Fehler in deinem Code auffällt. Könntest du da nochmal drüber schauen bitte?
Danke dir schonmal für die Hilfe :)

**Comment by leoniethomas** [comment]
Ich hab etwas an dem code verändert und ihn hochgepushed, sollte jtzt funktionieren. Wir können ja das nochmal morgen besprechen warum es jtzt funktioniert und vorher nicht
