### ISSUE TITLE
X-Shifts

### ISSUE THREAD

**Issue by MaikeH25** [datascience-mobi/2021-topic-03-team-05#6]
Hallo Leonie,
wir haben die Problemfunktion von gestern gelöst bekommen, d.h. darüber brauchst du dir keine Gedanken mehr zu machen. Jetzt wollen wir uns an die x-Shifts setzen und diese berechnen. Wir haben ja schon gestern darüber gesprochen, dass wir das am besten über die Häufigkeit, mit der ein Protein in unserer Matrix mit signifikanten Shifts vorkommt, machen sollten. Der Plan ist es gerade, eine Dataframe zu erstellen, in die erstmal nur alle Proteine reinkommen, die zwei Maxima haben, die signifikant geshiftet sind. Am besten so, dass in den Spalten der Proteinname und der x-Shift sind. Wir hängen allerdings gerade an zwei Stellen fest: zum einen kriegen wir es nicht so richtig hin, die Bedingung aufzustellen. Eigentlich ist diese ja "Wenn der Proteinname 2 Mal auftaucht, dann mache entsprechend was mit den Spalten, in denen auch der Proteinname auftaucht. Du hattest ja gestern von der grepl Funktion gesprochen, wir hatten das aber bisher so geplant, dass wir ein weiteres dataframe haben in dem einfach nur der Proteinname und die Häufigkeit drin stehen. Wie kriegen wir es denn jetzt aber hin, dass der entsprechende Proteinname auf das andere Dataframe, in dem unsere Fraktionen drin sind, anzuwenden? Wir haben dir mal ein Bild angehängt, damit du dir das vorstellen kannst
![20210708_132008836_iOS](https://user-images.githubusercontent.com/82653276/124928706-23ca1480-e000-11eb-9e48-8ff671368d5e.png)

Das zweite Problem ist dann das Erstellen einer neuen Dataframe. Wir haben bisher nur gefunden entweder, eine leere Dataframe zu definieren (dafür müssten wir ja aber vorher wissen, wie viele Proteine z.B. 2 mal vorkommen), cbind oder rbind. Cbind macht bei unserer Art der Darstellung keinen Sinn und bei rbind können wir ja nicht das typische "Vektoren bilden und aneinander binden" benutzen. Hast du da vielleicht noch eine andere Idee?

Danke dir schonmal!

**Comment by leoniethomas** [comment]
Ich schreib euch heute Abend noch ne Antwort:)

**Comment by leoniethomas** [comment]
![ex](https://user-images.githubusercontent.com/49941230/124994347-03bd4400-e046-11eb-820f-bcc8b1d284c9.png)

**Comment by leoniethomas** [comment]
also so könntet ihr immer die proteine extrahieren die eine bestimmte anzahl an Maxima haben. 
Zu dem 2. Punkt: mir ist noch nicht ganz klar wie die letztendliche dataframe aussehen soll, vilt könnt ihr mir das nochmal genauer erklären.
