### ISSUE TITLE
Funktionen definieren oder benutzen

### ISSUE THREAD

**Issue by GyuMinHwang** [datascience-mobi/2021-topic-03-team-05#7]
Hi Leonie, 

ich habe mich eben bisschen mit dem k-means clustering auseinander gesetzt. Und dabei ist mir aufgefallen, dass R ja eigentliche alle notwendigen Funktionen besitzt. Also natürlich die kmeans( )- aber dann auch silhouette( )-Funktion für die Silhouetten-Methode. Ich war mir jetzt nicht sicher, was wir benutzen sollen und eventuell dürfen, weil wir die kmeans() definitiv im 3S in der VL hatten und Silhoutten Plots nur inhaltlich ohne zugehörige Funktion besprochen hatten.

**Comment by leoniethomas** [comment]
Hi ihr, 
ja ihr dürft die k-means function benutzten, ihr solltet euch nur nochmal die Theorie zu den jeweiligen functionen ansehen, damit ihr das erklären könntet was da passiert
