### ISSUE TITLE
Tut am Mittwoch

### ISSUE THREAD

**Issue by hanaros27** [datascience-mobi/2021-topic-03-team-05#8]
Hallo Leonie! 
sorry, dass ich im letzten Moment frage, aber wäre es möglich, das Tutorium am Mittwoch (um 12) zu verschieben? Wir schreiben am selben Tag um 14 Uhr eine Klausur, daher wäre es uns lieber/weniger stressig, wenn das Tutorium am Abend oder am nächsten Tag stattfinden würde. 
Vielen Dank im Voraus!

**Comment by leoniethomas** [comment]
Würde euch 16:30 passen ?

**Comment by GyuMinHwang** [comment]
Hi ich glaube 16.30 wäre recht knapp, weil manche von uns nach der Klausur einen längeren Weg nach Hause haben.
Würde bei dir auch um 18Uhr passen?

**Comment by leoniethomas** [comment]
18 Uhr ist ein wenig zu spät, ginge 17:30 ?

**Comment by GyuMinHwang** [comment]
Jap das klappt auch:) dann bis 17:30Uhr
