### ISSUE TITLE
Probleme mit RBP Datenbanken

### ISSUE THREAD

**Issue by hanaros27** [datascience-mobi/2021-topic-03-team-05#9]
Hey Leonie,
hättest du zufällig heute oder morgen Zeit, um uns mit ein paar Kleinigkeiten durch Discord zu helfen?
Ich erkläre hier kurz eins von den vielen Problemen die wir gerade haben:
Nachdem wir mit folgendem Code die Proteine rausnehmen, die nicht in der Datenbank vorhanden sind, und vice versa, haben die 2 Dataframes trotzdem eine unterschiedliche Anzahl von Proteinen, nämlich die Datenbank hat 4 Proteine mehr, die wir aber nicht lokalisieren können. Die Funktion which() produziert einen leeren Vektor, und any() sagt, dass es keine Proteine gibt, die in einem Datensatz sind und im anderen nicht. Könnten wir vielleicht den Code mit dir zusammen durchgehen, wenn du Zeit hättest?

### Loading RBP database and our protein list

`RDeePDatabase <- read.table(paste0(path, "/table_RBP_lists.csv"), sep = ",", header=TRUE, skip = 6)`
`m_freqproteinname <- data.frame(table(m_shift_significant$`protein_name`))`

### Removing proteins not contained in the other data set

`RDeePDatabase <- RDeePDatabase[(RDeePDatabase$Entry_Name %in% m_freqproteinname$Var1),]`
`m_freqproteinname <- m_freqproteinname[(m_freqproteinname$Var1 %in% RDeePDatabase$Entry_Name),]`

### Creating operator "not in"

`%nin%` = Negate(`%in%`)
`which(RDeePDatabase$Entry_Name %nin% m_freqproteinname$Var1)
`

**Comment by leoniethomas** [comment]
geht 15 Uhr ?

**Comment by hanaros27** [comment]
ja, bis dann!:)
